spring.application.name=atencion-service
server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-billowing-union-aqhino3v.c-8.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_cL5P0jiZMlnQ&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cL5P0jiZMlnQ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.leak-detection-threshold=60000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration